version: "3"

services:
  app:
    container_name: ChatGPT-Line-Bot
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cqnhfnKw7
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db
