version: "3"

services:
  app:
    container_name: ChatGPT-Line-Bot
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db
