version: "3"

services:
  app:
    container_name: ChatGPT-Line-Bot
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cqnhfnK%w7
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/